VALIDATION_MESSAGES = {
    "missing":              "This field is required",
    "string_too_short":     "Value is too short",
    "string_too_long":      "Value is too long",
    "value_error":          "Invalid value",
    "type_error":           "Invalid type",
    "int_parsing":          "Must be a valid number",
    "float_parsing":        "Must be a valid number",
    "bool_parsing":         "Must be true or false",
    "email":                "Must be a valid email address",
    "url":                  "Must be a valid URL",
    "datetime_parsing":     "Must be a valid date and time",
    "date_parsing":         "Must be a valid date",
    "enum":                 "Invalid option selected",
    "greater_than":         "Value is too small",
    "less_than":            "Value is too large",
    "greater_than_equal":   "Value is too small",
    "less_than_equal":      "Value is too large",
}